version: '3'
services:
  tailscale:
    image: tailscale/tailscale
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: "host"
    privileged: true
    environment:
      - TAILSCALE_AUTHKEY=tskey-auth-kes2nF2CNTRL-FuA4U6jKK66Whhb3kt5s66kL7ZCJpk298
    restart: unless-stopped
